name: Goodlog Tests

on: [push, pull_request, merge_group, workflow_dispatch]

env:
  EVTX_BASELINE_VERSION: v0.8.4

jobs:
  check-baseline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Cache evtx-sigma-checker
      id: cache-evtx-checker
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
      with:
        path: evtx-sigma-checker
        key: evtx-sigma-checker-${{ env.EVTX_BASELINE_VERSION }}

    - name: Download evtx-sigma-checker
      if: steps.cache-evtx-checker.outputs.cache-hit != 'true'
      run: wget --no-verbose https://github.com/NextronSystems/evtx-baseline/releases/download/$EVTX_BASELINE_VERSION/evtx-sigma-checker

    - name: Set evtx-sigma-checker permissions
      run: chmod +x evtx-sigma-checker

    - name: Cache Windows 7 32-bit baseline
      id: cache-win7-x86
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
      with:
        path: win7-x86/
        key: baseline-win7-x86-${{ env.EVTX_BASELINE_VERSION }}

    - name: Download and extract Windows 7 32-bit baseline
      if: steps.cache-win7-x86.outputs.cache-hit != 'true'
      run: |
        wget --no-verbose https://github.com/NextronSystems/evtx-baseline/releases/download/$EVTX_BASELINE_VERSION/win7-x86.tgz
        tar xzf win7-x86.tgz

    - name: Cache Windows 10 baseline
      id: cache-win10-client
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
      with:
        path: Logs_Client/
        key: baseline-win10-client-${{ env.EVTX_BASELINE_VERSION }}

    - name: Download and extract Windows 10 baseline
      if: steps.cache-win10-client.outputs.cache-hit != 'true'
      run: |
        wget --no-verbose https://github.com/NextronSystems/evtx-baseline/releases/download/$EVTX_BASELINE_VERSION/win10-client.tgz
        tar xzf win10-client.tgz

    - name: Cache Windows 11 baseline
      id: cache-win11-client
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
      with:
        path: Logs_Win11/
        key: baseline-win11-client-${{ env.EVTX_BASELINE_VERSION }}

    - name: Download and extract Windows 11 baseline
      if: steps.cache-win11-client.outputs.cache-hit != 'true'
      run: |
        wget --no-verbose https://github.com/NextronSystems/evtx-baseline/releases/download/$EVTX_BASELINE_VERSION/win11-client.tgz
        tar xzf win11-client.tgz

    - name: Cache Windows 11 2023 baseline
      id: cache-win11-client-2023
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
      with:
        path: Logs_Win11_2023/
        key: baseline-win11-client-2023-${{ env.EVTX_BASELINE_VERSION }}

    - name: Download and extract Windows 11 2023 baseline
      if: steps.cache-win11-client-2023.outputs.cache-hit != 'true'
      run: |
        wget --no-verbose https://github.com/NextronSystems/evtx-baseline/releases/download/$EVTX_BASELINE_VERSION/win11-client-2023.tgz
        tar xzf win11-client-2023.tgz

    - name: Cache Windows 2022 baseline
      id: cache-win2022-evtx
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
      with:
        path: win2022-evtx/
        key: baseline-win2022-evtx-${{ env.EVTX_BASELINE_VERSION }}

    - name: Download and extract Windows 2022 baseline
      if: steps.cache-win2022-evtx.outputs.cache-hit != 'true'
      run: |
        wget --no-verbose https://github.com/NextronSystems/evtx-baseline/releases/download/$EVTX_BASELINE_VERSION/win2022-evtx.tgz
        tar xzf win2022-evtx.tgz

    - name: Cache Windows 2022 Domain Controller baseline
      id: cache-win2022-ad
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
      with:
        path: Win2022-AD/
        key: baseline-win2022-ad-${{ env.EVTX_BASELINE_VERSION }}

    - name: Download and extract Windows 2022 Domain Controller baseline
      if: steps.cache-win2022-ad.outputs.cache-hit != 'true'
      run: |
        wget --no-verbose https://github.com/NextronSystems/evtx-baseline/releases/download/$EVTX_BASELINE_VERSION/win2022-ad.tgz
        tar xzf win2022-ad.tgz

    - name: Cache Windows 2022 Azure baseline
      id: cache-win2022-azure
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
      with:
        path: win2022-0-20348-azure/
        key: baseline-win2022-0-20348-azure-${{ env.EVTX_BASELINE_VERSION }}

    - name: Download and extract Windows 2022 Azure baseline
      if: steps.cache-win2022-azure.outputs.cache-hit != 'true'
      run: |
        wget --no-verbose https://github.com/NextronSystems/evtx-baseline/releases/download/$EVTX_BASELINE_VERSION/win2022-0-20348-azure.tgz
        tar xzf win2022-0-20348-azure.tgz

    - name: Check for Sigma matches in baselines
      run: |
        ./evtx-sigma-checker \
          --log-source tests/thor.yml \
          --evtx-path win7-x86/ \
          --evtx-path Logs_Client/ \
          --evtx-path Logs_Win11/ \
          --evtx-path Logs_Win11_2023/ \
          --evtx-path win2022-evtx/ \
          --evtx-path Win2022-AD/ \
          --evtx-path win2022-0-20348-azure/ \
          --rule-path rules/windows/ \
          --rule-path rules-emerging-threats/ \
          --rule-path rules-threat-hunting/ \
          > findings.json

    - name: Validate findings against known FPs
      run: python tests/run_goodlog_tests.py --findings findings.json --known-fps .github/workflows/known-FPs.csv
